function openDownloads(){
    document
    .querySelectorAll(".page")
    .forEach(page=>{
        page.classList.remove("active");
    });
    document
    .getElementById("scripts")
    .classList.add("active");
    document
    .querySelectorAll(".tab")
    .forEach(btn=>{
        btn.classList.remove("active");
    });
    document
    .getElementById("downloadTab")
    .classList.add("active");
    document
    .getElementById("scripts")
    .scrollIntoView({
        behavior:"smooth"
    });
}